name: PHP CI/CD

on:
  push:
    branches:
      - main

jobs:
  php-tests:
    name: PHP Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Run PHP Lint (all files)
        run: |
          find . -type f -name "*.php" -print0 | xargs -0 -n1 php -l

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: php-tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
